services:
  postgres:
    image: postgres:18.4-alpine
    container_name: cicdpostgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cicd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8.8.0-alpine
    container_name: cicdredis
    ports:
      - "6379:6379"

volumes:
  postgres_data: