// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    pipeline_id,
    status,
    name,
    order_index
)
VALUES (
    $1,$2,$3,$4
)
RETURNING id, pipeline_id, name, status, started_at, finished_at, order_index, created_at, updated_at
`

type CreateJobParams struct {
	PipelineID int64     `json:"pipeline_id"`
	Status     JobStatus `json:"status"`
	Name       string    `json:"name"`
	OrderIndex int32     `json:"order_index"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.PipelineID,
		arg.Status,
		arg.Name,
		arg.OrderIndex,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJobsByPipeline = `-- name: ListJobsByPipeline :many
SELECT j.id, j.pipeline_id, j.name, j.status, j.started_at, j.finished_at, j.order_index, j.created_at, j.updated_at FROM jobs j
JOIN pipelines p ON j.pipeline_id = p.id
JOIN repositories r ON p.repository_id = r.id
WHERE j.pipeline_id = $1 AND r.user_id = $2
`

type ListJobsByPipelineParams struct {
	PipelineID int64 `json:"pipeline_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) ListJobsByPipeline(ctx context.Context, arg ListJobsByPipelineParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByPipeline, arg.PipelineID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByPipelineInternal = `-- name: ListJobsByPipelineInternal :many
SELECT id, pipeline_id, name, status, started_at, finished_at, order_index, created_at, updated_at FROM jobs
WHERE pipeline_id = $1
`

func (q *Queries) ListJobsByPipelineInternal(ctx context.Context, pipelineID int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByPipelineInternal, pipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET
    status = $1,
    started_at = COALESCE($2, started_at),
    finished_at = COALESCE($3, finished_at),
    updated_at = NOW()
WHERE id = $4
RETURNING id, pipeline_id, name, status, started_at, finished_at, order_index, created_at, updated_at
`

type UpdateJobStatusParams struct {
	Status     JobStatus          `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         int64              `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
