// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID          int64            `json:"id"`
	PipelineID  int64            `json:"pipeline_id"`
	Name        string           `json:"name"`
	Status      string           `json:"status"`
	StartedAt   pgtype.Timestamp `json:"started_at"`
	CompletedAt pgtype.Timestamp `json:"completed_at"`
}

type Log struct {
	ID        int64            `json:"id"`
	JobID     int64            `json:"job_id"`
	Content   pgtype.Text      `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Pipeline struct {
	ID           int64            `json:"id"`
	RepositoryID int64            `json:"repository_id"`
	CommitSha    pgtype.Text      `json:"commit_sha"`
	Branch       pgtype.Text      `json:"branch"`
	Status       string           `json:"status"`
	TriggerType  pgtype.Text      `json:"trigger_type"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	StartedAt    pgtype.Timestamp `json:"started_at"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}

type Repository struct {
	ID            int64            `json:"id"`
	Name          string           `json:"name"`
	GithubUrl     string           `json:"github_url"`
	DefaultBranch pgtype.Text      `json:"default_branch"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}
