// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipelines.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipelines (
    repository_id,
    github_delivery_id,
    commit_sha,
    commit_message,
    branch,
    event_type,
    trigger_username
)
VALUES (
    $1,$2,$3,$4,$5,$6,$7
)
RETURNING id, repository_id, commit_sha, commit_message, branch, event_type, status, created_at, started_at, finished_at, github_delivery_id, trigger_username, updated_at
`

type CreatePipelineParams struct {
	RepositoryID     int64       `json:"repository_id"`
	GithubDeliveryID pgtype.Text `json:"github_delivery_id"`
	CommitSha        string      `json:"commit_sha"`
	CommitMessage    pgtype.Text `json:"commit_message"`
	Branch           string      `json:"branch"`
	EventType        GithubEvent `json:"event_type"`
	TriggerUsername  pgtype.Text `json:"trigger_username"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, createPipeline,
		arg.RepositoryID,
		arg.GithubDeliveryID,
		arg.CommitSha,
		arg.CommitMessage,
		arg.Branch,
		arg.EventType,
		arg.TriggerUsername,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Branch,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.GithubDeliveryID,
		&i.TriggerUsername,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineById = `-- name: GetPipelineById :one
SELECT p.id, p.repository_id, p.commit_sha, p.commit_message, p.branch, p.event_type, p.status, p.created_at, p.started_at, p.finished_at, p.github_delivery_id, p.trigger_username, p.updated_at FROM pipelines p
JOIN repositories r ON p.repository_id = r.id
WHERE p.id = $1 AND r.user_id = $2
`

type GetPipelineByIdParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetPipelineById(ctx context.Context, arg GetPipelineByIdParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipelineById, arg.ID, arg.UserID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Branch,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.GithubDeliveryID,
		&i.TriggerUsername,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineByIdInternal = `-- name: GetPipelineByIdInternal :one
SELECT id, repository_id, commit_sha, commit_message, branch, event_type, status, created_at, started_at, finished_at, github_delivery_id, trigger_username, updated_at FROM pipelines
WHERE id = $1
`

func (q *Queries) GetPipelineByIdInternal(ctx context.Context, id int64) (Pipeline, error) {
	row := q.db.QueryRow(ctx, getPipelineByIdInternal, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Branch,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.GithubDeliveryID,
		&i.TriggerUsername,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositoryPipelines = `-- name: ListRepositoryPipelines :many
SELECT p.id, p.repository_id, p.commit_sha, p.commit_message, p.branch, p.event_type, p.status, p.created_at, p.started_at, p.finished_at, p.github_delivery_id, p.trigger_username, p.updated_at FROM pipelines p
JOIN repositories r ON p.repository_id = r.id
WHERE p.repository_id = $1 AND r.user_id = $2
ORDER BY p.created_at DESC
`

type ListRepositoryPipelinesParams struct {
	RepositoryID int64 `json:"repository_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) ListRepositoryPipelines(ctx context.Context, arg ListRepositoryPipelinesParams) ([]Pipeline, error) {
	rows, err := q.db.Query(ctx, listRepositoryPipelines, arg.RepositoryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipeline{}
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.CommitSha,
			&i.CommitMessage,
			&i.Branch,
			&i.EventType,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.GithubDeliveryID,
			&i.TriggerUsername,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePipelineStatus = `-- name: UpdatePipelineStatus :one
UPDATE pipelines
SET
    status = $1,
    started_at = COALESCE($2, started_at),
    finished_at = COALESCE($3, finished_at),
    updated_at = NOW()
WHERE id = $4
RETURNING id, repository_id, commit_sha, commit_message, branch, event_type, status, created_at, started_at, finished_at, github_delivery_id, trigger_username, updated_at
`

type UpdatePipelineStatusParams struct {
	Status     PipelineStatus     `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ID         int64              `json:"id"`
}

func (q *Queries) UpdatePipelineStatus(ctx context.Context, arg UpdatePipelineStatusParams) (Pipeline, error) {
	row := q.db.QueryRow(ctx, updatePipelineStatus,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Branch,
		&i.EventType,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.GithubDeliveryID,
		&i.TriggerUsername,
		&i.UpdatedAt,
	)
	return i, err
}
