// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateGithubToken(ctx context.Context, arg CreateGithubTokenParams) (GithubToken, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRepository(ctx context.Context, id int64) error
	FindByGithubUrl(ctx context.Context, githubUrl string) (Repository, error)
	GetGithubToken(ctx context.Context, userID int64) (GithubToken, error)
	GetRepository(ctx context.Context, name string) (Repository, error)
	GetUserByGithubID(ctx context.Context, githubID int64) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListRepositories(ctx context.Context) ([]Repository, error)
	UpdateGithubToken(ctx context.Context, arg UpdateGithubTokenParams) (GithubToken, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
