// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repository_jobs.sql

package sqlc

import (
	"context"
)

const createRepositoryJobTemplate = `-- name: CreateRepositoryJobTemplate :one
INSERT INTO repository_job_templates (
    repository_id,
    name,
    order_index,
    image,
    working_directory,
    commands
)
VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, repository_id, name, order_index, image, working_directory, commands, created_at, updated_at
`

type CreateRepositoryJobTemplateParams struct {
	RepositoryID     int64    `json:"repository_id"`
	Name             string   `json:"name"`
	OrderIndex       int32    `json:"order_index"`
	Image            string   `json:"image"`
	WorkingDirectory string   `json:"working_directory"`
	Commands         []string `json:"commands"`
}

func (q *Queries) CreateRepositoryJobTemplate(ctx context.Context, arg CreateRepositoryJobTemplateParams) (RepositoryJobTemplate, error) {
	row := q.db.QueryRow(ctx, createRepositoryJobTemplate,
		arg.RepositoryID,
		arg.Name,
		arg.OrderIndex,
		arg.Image,
		arg.WorkingDirectory,
		arg.Commands,
	)
	var i RepositoryJobTemplate
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Name,
		&i.OrderIndex,
		&i.Image,
		&i.WorkingDirectory,
		&i.Commands,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepositoryJobTemplatesByRepo = `-- name: DeleteRepositoryJobTemplatesByRepo :exec
DELETE FROM repository_job_templates
WHERE repository_id = $1
`

func (q *Queries) DeleteRepositoryJobTemplatesByRepo(ctx context.Context, repositoryID int64) error {
	_, err := q.db.Exec(ctx, deleteRepositoryJobTemplatesByRepo, repositoryID)
	return err
}

const listRepositoryJobTemplates = `-- name: ListRepositoryJobTemplates :many
SELECT t.id, t.repository_id, t.name, t.order_index, t.image, t.working_directory, t.commands, t.created_at, t.updated_at FROM repository_job_templates t
JOIN repositories r ON t.repository_id = r.id
WHERE t.repository_id = $1 AND r.user_id = $2
ORDER BY t.order_index ASC
`

type ListRepositoryJobTemplatesParams struct {
	RepositoryID int64 `json:"repository_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) ListRepositoryJobTemplates(ctx context.Context, arg ListRepositoryJobTemplatesParams) ([]RepositoryJobTemplate, error) {
	rows, err := q.db.Query(ctx, listRepositoryJobTemplates, arg.RepositoryID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepositoryJobTemplate{}
	for rows.Next() {
		var i RepositoryJobTemplate
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.OrderIndex,
			&i.Image,
			&i.WorkingDirectory,
			&i.Commands,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryJobTemplatesInternal = `-- name: ListRepositoryJobTemplatesInternal :many
SELECT id, repository_id, name, order_index, image, working_directory, commands, created_at, updated_at FROM repository_job_templates
WHERE repository_id = $1
ORDER BY order_index ASC
`

func (q *Queries) ListRepositoryJobTemplatesInternal(ctx context.Context, repositoryID int64) ([]RepositoryJobTemplate, error) {
	rows, err := q.db.Query(ctx, listRepositoryJobTemplatesInternal, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepositoryJobTemplate{}
	for rows.Next() {
		var i RepositoryJobTemplate
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.Name,
			&i.OrderIndex,
			&i.Image,
			&i.WorkingDirectory,
			&i.Commands,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
