// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package sqlc

import (
	"context"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (name, github_url, default_branch)
VALUES ($1, $2, $3) RETURNING id, owner_id, github_repo_id, name, full_name, github_url, default_branch, private, webhook_id, webhook_active, created_at, updated_at
`

type CreateRepositoryParams struct {
	Name          string `json:"name"`
	GithubUrl     string `json:"github_url"`
	DefaultBranch string `json:"default_branch"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository, arg.Name, arg.GithubUrl, arg.DefaultBranch)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GithubRepoID,
		&i.Name,
		&i.FullName,
		&i.GithubUrl,
		&i.DefaultBranch,
		&i.Private,
		&i.WebhookID,
		&i.WebhookActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories WHERE id = $1
`

func (q *Queries) DeleteRepository(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRepository, id)
	return err
}

const findByGithubUrl = `-- name: FindByGithubUrl :one
SELECT id, owner_id, github_repo_id, name, full_name, github_url, default_branch, private, webhook_id, webhook_active, created_at, updated_at FROM repositories 
WHERE github_url = $1
`

func (q *Queries) FindByGithubUrl(ctx context.Context, githubUrl string) (Repository, error) {
	row := q.db.QueryRow(ctx, findByGithubUrl, githubUrl)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GithubRepoID,
		&i.Name,
		&i.FullName,
		&i.GithubUrl,
		&i.DefaultBranch,
		&i.Private,
		&i.WebhookID,
		&i.WebhookActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepository = `-- name: GetRepository :one
SELECT id, owner_id, github_repo_id, name, full_name, github_url, default_branch, private, webhook_id, webhook_active, created_at, updated_at FROM repositories 
WHERE name = $1
`

func (q *Queries) GetRepository(ctx context.Context, name string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, name)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.GithubRepoID,
		&i.Name,
		&i.FullName,
		&i.GithubUrl,
		&i.DefaultBranch,
		&i.Private,
		&i.WebhookID,
		&i.WebhookActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, owner_id, github_repo_id, name, full_name, github_url, default_branch, private, webhook_id, webhook_active, created_at, updated_at FROM repositories 
ORDER BY created_at DESC
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.GithubRepoID,
			&i.Name,
			&i.FullName,
			&i.GithubUrl,
			&i.DefaultBranch,
			&i.Private,
			&i.WebhookID,
			&i.WebhookActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
