// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package sqlc

import (
	"context"
)

const createGithubToken = `-- name: CreateGithubToken :one
INSERT INTO github_tokens (user_id, access_token)
VALUES ($1, $2) RETURNING user_id, access_token, created_at, updated_at
`

type CreateGithubTokenParams struct {
	UserID      int64  `json:"user_id"`
	AccessToken string `json:"access_token"`
}

func (q *Queries) CreateGithubToken(ctx context.Context, arg CreateGithubTokenParams) (GithubToken, error) {
	row := q.db.QueryRow(ctx, createGithubToken, arg.UserID, arg.AccessToken)
	var i GithubToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubToken = `-- name: GetGithubToken :one
SELECT access_token
FROM github_tokens
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetGithubToken(ctx context.Context, userID int64) (string, error) {
	row := q.db.QueryRow(ctx, getGithubToken, userID)
	var access_token string
	err := row.Scan(&access_token)
	return access_token, err
}

const updateGithubToken = `-- name: UpdateGithubToken :one
UPDATE github_tokens SET access_token = $2, updated_at = NOW()
WHERE user_id = $1 RETURNING user_id, access_token, created_at, updated_at
`

type UpdateGithubTokenParams struct {
	UserID      int64  `json:"user_id"`
	AccessToken string `json:"access_token"`
}

func (q *Queries) UpdateGithubToken(ctx context.Context, arg UpdateGithubTokenParams) (GithubToken, error) {
	row := q.db.QueryRow(ctx, updateGithubToken, arg.UserID, arg.AccessToken)
	var i GithubToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
