// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package sqlc

import (
	"context"
)

const createToken = `-- name: CreateToken :one
INSERT INTO github_tokens (user_id, access_token)
VALUES ($1, $2) RETURNING user_id, access_token, created_at, updated_at
`

type CreateTokenParams struct {
	UserID      int64  `json:"user_id"`
	AccessToken string `json:"access_token"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (GithubToken, error) {
	row := q.db.QueryRow(ctx, createToken, arg.UserID, arg.AccessToken)
	var i GithubToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateToken = `-- name: UpdateToken :one
UPDATE github_tokens SET access_token = $2, updated_at = NOW()
WHERE user_id = $1 RETURNING user_id, access_token, created_at, updated_at
`

type UpdateTokenParams struct {
	UserID      int64  `json:"user_id"`
	AccessToken string `json:"access_token"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) (GithubToken, error) {
	row := q.db.QueryRow(ctx, updateToken, arg.UserID, arg.AccessToken)
	var i GithubToken
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
